### ISSUE TITLE
speedup-button title: The first letter should be capitalized

### ISSUE THREAD

**Issue by jwalteri** [haerrel/bbb-playbackspeed-chrome-extension#1]
![grafik](https://user-images.githubusercontent.com/43862813/79393929-99b70b80-7f76-11ea-9fa0-defdd2447d9e.png)

For tooltips the first letter should be capitalized.
Please change the tooltip according to the standard.

**Comment by jwalteri** [comment]
@haerrel Needs fix.

**Comment by haerrel** [comment]
@jwalteri Submit PR please.

**Comment by jwalteri** [comment]
@haerrel I have forwarded the ticket to the dev team. Fix coming soon!
